= Deploy to Cloud Foundry

This document contains instructions for deploying the sample service broker to a Cloud Foundry foundation.

All instructions below assume that the commands are being run from the root of the project repository.

= Prerequisites

== Cloud Foundry CLI

These instructions use the `cf` CLI to interact with a running Cloud Foundry foundation.
Follow the https://docs.cloudfoundry.org/cf-cli/[`cf` documentation] to install and verify the CLI.

== Cloud Foundry foundation

A Cloud Foundry foundation will be used to deploy the service broker application and register it to the service marketplace.
This can be a public hosted Cloud Foundry, a private Cloud Foundry, or a workstation-deployed Cloud Foundry like https://github.com/cloudfoundry-incubator/cfdev[CF Dev] or https://pivotal.io/pcf-dev[PCF Dev].

Use the `cf` CLI to https://docs.cloudfoundry.org/cf-cli/getting-started.html#login[log into] Cloud Foundry and target an organization and space for deployment of an application.

= Build the service broker application

The Gradle build file for the service broker sample project can be used to build the application.

----
$ ./gradlew assemble
----

= Deploy and test the service broker

== Deploy the service broker application

Deploy the service broker application to Cloud Foundry:

----
$ cf push -f deploy/cloudfoundry/manifest.yml
Pushing from manifest to org sample / space test as user@example.com...
Using manifest file deploy/cloudfoundry/manifest.yml
Getting app info...
Creating app with these attributes...
+ name:       route-service-broker
  path:       build/libs/route-service-broker-0.0.1.BUILD-SNAPSHOT.jar
+ memory:     1G
  routes:
+   route-service-broker.apps.example.com

...

name:              route-service-broker
requested state:   started
instances:         1/1
usage:             1G x 1 instances
routes:            route-service-broker.apps.example.com

...

      state     since                  cpu    memory         disk           details
#0   running   2018-02-13T21:58:44Z   0.0%   290.8M of 1G   144.7M of 1G
----

== Verify the service broker application

Note the value of the `route` row in the output from the command above.
Use this route to build a URL to access the `/v2/catalog` endpoint of the service broker application.

----
$ curl https://route-service-broker.apps.example.com/v2/catalog -u admin:supersecret
{"services":[{"id":"d897c845-e15e-467e-9c34-71632e8807e1","name":"route-logger","description":"A simple route logging service","bindable":true,"plan_updateable":false,"instances_retrievable":false,"bindings_retrievable":false,"plans":[{"id":"3944a61c-ed68-45c5-b649-a99d1f301c69","name":"standard","description":"A simple plan","metadata":{},"bindable":true,"free":true}],"tags":["route-service","logging"],"metadata":{},"requires":["route_forwarding"]}]}
----

= Register and test the service broker

== Register to the services marketplace

Now that the application has been deployed and verified, it can be registered to the Cloud Foundry services marketplace.

=== With administrator privileges

If you have administrator privileges on Cloud Foundry, you can make the service broker available in all organizations and spaces.

The Open Service Broker API endpoints in the service broker application are secured with a basic auth username and password.
Register the service broker using the URL from above and the credentials:

----
$ cf create-service-broker route-service admin supersecret https://route-service-broker.apps.example.com
Creating service broker route-service as admin...
OK
----

Make the service offerings from the service broker visible in the services marketplace:

----
$ cf enable-service-access route-service
Enabling access to all plans of service route-service for all orgs as admin...
OK
----

=== Without administrator privileges

If you do not have administrator privileges on Cloud Foundry, you can make the service broker available in a single organization and space that you have privileges in:

----
$ cf create-service-broker route-service admin supersecret https://route-service-broker.apps.example.com --space-scoped
Creating service broker route-service in org sample / space test as user@example.com...
OK
----

== View to the services marketplace

Show the services marketplace:

----
$ cf marketplace
Getting services from marketplace in org sample / space test as user@example.com...
OK

service                       plans                 description
route-service                 standard              A simple route logging service

TIP:  Use 'cf marketplace -s SERVICE' to view descriptions of individual plans of a given service.
----

----
$ cf marketplace -s route-service
Getting service plan information for service route-service as user@example.com...
OK

service plan   description               free or paid
standard       A simple plan             free
----

= Use the service broker

== Create a service instance

Create an instance of a route service from the sample service broker:

----
$ cf create-service route-service standard my-route-service
Creating service instance my-route-service in org sample / space test as user@example.com...
OK
----

Show the details of the created service instance:

----
$ cf service my-route-service
Showing info of service my-route-service in org sample / space test as user@example.com...

name:            route-service
service:         my-route-service
tags:
plan:            standard
description:     A simple route logging service
documentation:
dashboard:

There are no bound apps for this service.

Showing status of last operation from service my-route-service...

status:    create succeeded
message:
----

== Bind the service instance to an application

Push any application to Cloud Foundry and bind a route to it.
The examples below assume that the domain `apps.example.com` exists in Cloud Foundry, and that the application has a route `appname.apps.example.com` bound to it.

Bind the service instance to the application:

----
$ cf bind-route-service apps.example.com my-route-service --hostname appname
Binding route appname.apps.example.com to service instance my-route-service in org sample / space test as user@example.com...
OK
----

Send any request to the application that the service instance is bound to:
----
$ curl https://appname.apps.example.com
----

View the logs of the service broker to verify that it intercepted the request to the application and logged it:

----
$ cf logs route-service-broker --recent
Retrieving logs for app route-service-broker in org sample / space test as user@example.com... 
...
2018-04-25T13:04:56.77-0500 [APP/PROC/WEB/0] OUT 2018-04-25 18:04:56.773  INFO 15 --- [ctor-http-nio-3] o.s.c.s.r.f.LoggingGatewayFilterFactory  : Forwarding request: method=GET, headers={Host=[route-service-broker.apps.example.com], User-Agent=[curl/7.54.0], Accept=[*/*], X-B3-Spanid=[409cc4b017fb5936], X-B3-Traceid=[409cc4b017fb5936], X-Cf-Applicationid=[292e5ec7-0608-4c0d-b5fb-de83f9377446], X-Cf-Forwarded-Url=[https://appname.apps.example.com/actuator/info], X-Cf-Instanceid=[2452da9e-04c2-4077-5d0a-5a42], X-Cf-Instanceindex=[0], X-Cf-Proxy-Metadata=[eyJub25jZSI6InRNY1JtMGVQcGN5ZlNNNFEifQ==], X-Cf-Proxy-Signature=[yD8H40mQkoJwXMMChhRJXrwGv0346YQrLsHdeWw8C7cIRC-F2I5AJEsdRh9QtHFnwIq_mHavUUsVXtsVEiWOFUDBnZaXtC_JtisumCtLelsNQj3ytgbhezzqiUOScyv-wc1jxw9HT0EjcRhFNEE1-hoxF26bFVFNWSXuj4D7BY2wnDUdgpVQmrOo1wKs7GIue3I89WPfCMR3EnY5oHQ9], X-Forwarded-For=[192.168.1.1, 192.168.1.97, 127.0.0.1], X-Forwarded-Host=[appname.apps.example.com], X-Forwarded-Proto=[https], X-Forwarded-Server=[cf.example.com], X-Request-Start=[1524679496744], X-Vcap-Request-Id=[17782e7c-d307-4556-7c35-d1b21b2fc38b]}, url=https://appname.apps.example.com
2018-04-25T13:04:56.87-0500 [APP/PROC/WEB/0] OUT 2018-04-25 18:04:56.872  INFO 15 --- [ctor-http-nio-1] o.s.c.s.r.f.LoggingGatewayFilterFactory  : Response: method=GET, headers={Host=[route-service-broker.apps.example.com], User-Agent=[curl/7.54.0], Accept=[*/*], X-B3-Spanid=[409cc4b017fb5936], X-B3-Traceid=[409cc4b017fb5936], X-Cf-Applicationid=[292e5ec7-0608-4c0d-b5fb-de83f9377446], X-Cf-Forwarded-Url=[https://appname.apps.example.com/actuator/info], X-Cf-Instanceid=[2452da9e-04c2-4077-5d0a-5a42], X-Cf-Instanceindex=[0], X-Cf-Proxy-Metadata=[eyJub25jZSI6InRNY1JtMGVQcGN5ZlNNNFEifQ==], X-Cf-Proxy-Signature=[yD8H40mQkoJwXMMChhRJXrwGv0346YQrLsHdeWw8C7cIRC-F2I5AJEsdRh9QtHFnwIq_mHavUUsVXtsVEiWOFUDBnZaXtC_JtisumCtLelsNQj3ytgbhezzqiUOScyv-wc1jxw9HT0EjcRhFNEE1-hoxF26bFVFNWSXuj4D7BY2wnDUdgpVQmrOo1wKs7GIue3I89WPfCMR3EnY5oHQ9], X-Forwarded-For=[192.168.1.1, 192.168.1.97, 127.0.0.1], X-Forwarded-Host=[appname.apps.example.com], X-Forwarded-Proto=[https], X-Forwarded-Server=[cf.example.com], X-Request-Start=[1524679496744], X-Vcap-Request-Id=[17782e7c-d307-4556-7c35-d1b21b2fc38b]}, url=https://appname.apps.example.com
...
----
